//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.10 at 08:34:16 PM IST 
//


package com.redowl.batch_processing.xmlProceser.xmlConfigDto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for report_indicator_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="report_indicator_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A1"/&gt;
 *     &lt;enumeration value="A2"/&gt;
 *     &lt;enumeration value="AIF"/&gt;
 *     &lt;enumeration value="AIFT"/&gt;
 *     &lt;enumeration value="B1"/&gt;
 *     &lt;enumeration value="B2"/&gt;
 *     &lt;enumeration value="B3"/&gt;
 *     &lt;enumeration value="B4"/&gt;
 *     &lt;enumeration value="B5"/&gt;
 *     &lt;enumeration value="B6"/&gt;
 *     &lt;enumeration value="B7"/&gt;
 *     &lt;enumeration value="BRS"/&gt;
 *     &lt;enumeration value="BRSC"/&gt;
 *     &lt;enumeration value="C1"/&gt;
 *     &lt;enumeration value="C2"/&gt;
 *     &lt;enumeration value="C3"/&gt;
 *     &lt;enumeration value="C4"/&gt;
 *     &lt;enumeration value="C5"/&gt;
 *     &lt;enumeration value="C6"/&gt;
 *     &lt;enumeration value="C7"/&gt;
 *     &lt;enumeration value="CFIR1"/&gt;
 *     &lt;enumeration value="CFIR2"/&gt;
 *     &lt;enumeration value="CFIR3"/&gt;
 *     &lt;enumeration value="CTR"/&gt;
 *     &lt;enumeration value="D1"/&gt;
 *     &lt;enumeration value="E1"/&gt;
 *     &lt;enumeration value="EFT"/&gt;
 *     &lt;enumeration value="F1"/&gt;
 *     &lt;enumeration value="FP"/&gt;
 *     &lt;enumeration value="IFT"/&gt;
 *     &lt;enumeration value="LKFNS"/&gt;
 *     &lt;enumeration value="OTH"/&gt;
 *     &lt;enumeration value="PAER1"/&gt;
 *     &lt;enumeration value="RAPS1"/&gt;
 *     &lt;enumeration value="RAPS2"/&gt;
 *     &lt;enumeration value="RAPS3"/&gt;
 *     &lt;enumeration value="RAPS4"/&gt;
 *     &lt;enumeration value="RAPS5"/&gt;
 *     &lt;enumeration value="S01"/&gt;
 *     &lt;enumeration value="S02"/&gt;
 *     &lt;enumeration value="SB01"/&gt;
 *     &lt;enumeration value="SB02"/&gt;
 *     &lt;enumeration value="SB03"/&gt;
 *     &lt;enumeration value="SB04"/&gt;
 *     &lt;enumeration value="SB05"/&gt;
 *     &lt;enumeration value="SB06"/&gt;
 *     &lt;enumeration value="SB07"/&gt;
 *     &lt;enumeration value="SB08"/&gt;
 *     &lt;enumeration value="SB09"/&gt;
 *     &lt;enumeration value="SB10"/&gt;
 *     &lt;enumeration value="SB11"/&gt;
 *     &lt;enumeration value="SB13"/&gt;
 *     &lt;enumeration value="SB14"/&gt;
 *     &lt;enumeration value="SB16"/&gt;
 *     &lt;enumeration value="SB17"/&gt;
 *     &lt;enumeration value="SB19"/&gt;
 *     &lt;enumeration value="SB20"/&gt;
 *     &lt;enumeration value="SB21"/&gt;
 *     &lt;enumeration value="SB22"/&gt;
 *     &lt;enumeration value="SB23"/&gt;
 *     &lt;enumeration value="SB25"/&gt;
 *     &lt;enumeration value="SB26"/&gt;
 *     &lt;enumeration value="SB27"/&gt;
 *     &lt;enumeration value="SB28"/&gt;
 *     &lt;enumeration value="SB29"/&gt;
 *     &lt;enumeration value="SB30"/&gt;
 *     &lt;enumeration value="SB31"/&gt;
 *     &lt;enumeration value="SB32"/&gt;
 *     &lt;enumeration value="SB33"/&gt;
 *     &lt;enumeration value="SB34"/&gt;
 *     &lt;enumeration value="SB35"/&gt;
 *     &lt;enumeration value="SB36"/&gt;
 *     &lt;enumeration value="SB37"/&gt;
 *     &lt;enumeration value="SB38"/&gt;
 *     &lt;enumeration value="SB39"/&gt;
 *     &lt;enumeration value="SB40"/&gt;
 *     &lt;enumeration value="SB41"/&gt;
 *     &lt;enumeration value="SB42"/&gt;
 *     &lt;enumeration value="SB43"/&gt;
 *     &lt;enumeration value="SB44"/&gt;
 *     &lt;enumeration value="SB45"/&gt;
 *     &lt;enumeration value="SB46"/&gt;
 *     &lt;enumeration value="SB47"/&gt;
 *     &lt;enumeration value="SB48"/&gt;
 *     &lt;enumeration value="SB49"/&gt;
 *     &lt;enumeration value="SB50"/&gt;
 *     &lt;enumeration value="SB51"/&gt;
 *     &lt;enumeration value="TBA1"/&gt;
 *     &lt;enumeration value="TBA2"/&gt;
 *     &lt;enumeration value="TBA3"/&gt;
 *     &lt;enumeration value="TBA4"/&gt;
 *     &lt;enumeration value="TBA5"/&gt;
 *     &lt;enumeration value="TBA6"/&gt;
 *     &lt;enumeration value="TBA7"/&gt;
 *     &lt;enumeration value="TBD1"/&gt;
 *     &lt;enumeration value="TBD2"/&gt;
 *     &lt;enumeration value="TBD3"/&gt;
 *     &lt;enumeration value="TBD4"/&gt;
 *     &lt;enumeration value="TBD5"/&gt;
 *     &lt;enumeration value="TBD6"/&gt;
 *     &lt;enumeration value="TBD9"/&gt;
 *     &lt;enumeration value="TBT1"/&gt;
 *     &lt;enumeration value="TBT10"/&gt;
 *     &lt;enumeration value="TBT11"/&gt;
 *     &lt;enumeration value="TBT12"/&gt;
 *     &lt;enumeration value="TBT13"/&gt;
 *     &lt;enumeration value="TBT2"/&gt;
 *     &lt;enumeration value="TBT3"/&gt;
 *     &lt;enumeration value="TBT4"/&gt;
 *     &lt;enumeration value="TBT5"/&gt;
 *     &lt;enumeration value="TBT6"/&gt;
 *     &lt;enumeration value="TBT7"/&gt;
 *     &lt;enumeration value="TBT8"/&gt;
 *     &lt;enumeration value="TBT9"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "report_indicator_type")
@XmlEnum
public enum ReportIndicatorType {

    @XmlEnumValue("A1")
    A_1("A1"),
    @XmlEnumValue("A2")
    A_2("A2"),
    AIF("AIF"),
    AIFT("AIFT"),
    @XmlEnumValue("B1")
    B_1("B1"),
    @XmlEnumValue("B2")
    B_2("B2"),
    @XmlEnumValue("B3")
    B_3("B3"),
    @XmlEnumValue("B4")
    B_4("B4"),
    @XmlEnumValue("B5")
    B_5("B5"),
    @XmlEnumValue("B6")
    B_6("B6"),
    @XmlEnumValue("B7")
    B_7("B7"),
    BRS("BRS"),
    BRSC("BRSC"),
    @XmlEnumValue("C1")
    C_1("C1"),
    @XmlEnumValue("C2")
    C_2("C2"),
    @XmlEnumValue("C3")
    C_3("C3"),
    @XmlEnumValue("C4")
    C_4("C4"),
    @XmlEnumValue("C5")
    C_5("C5"),
    @XmlEnumValue("C6")
    C_6("C6"),
    @XmlEnumValue("C7")
    C_7("C7"),
    @XmlEnumValue("CFIR1")
    CFIR_1("CFIR1"),
    @XmlEnumValue("CFIR2")
    CFIR_2("CFIR2"),
    @XmlEnumValue("CFIR3")
    CFIR_3("CFIR3"),
    CTR("CTR"),
    @XmlEnumValue("D1")
    D_1("D1"),
    @XmlEnumValue("E1")
    E_1("E1"),
    EFT("EFT"),
    @XmlEnumValue("F1")
    F_1("F1"),
    FP("FP"),
    IFT("IFT"),
    LKFNS("LKFNS"),
    OTH("OTH"),
    @XmlEnumValue("PAER1")
    PAER_1("PAER1"),
    @XmlEnumValue("RAPS1")
    RAPS_1("RAPS1"),
    @XmlEnumValue("RAPS2")
    RAPS_2("RAPS2"),
    @XmlEnumValue("RAPS3")
    RAPS_3("RAPS3"),
    @XmlEnumValue("RAPS4")
    RAPS_4("RAPS4"),
    @XmlEnumValue("RAPS5")
    RAPS_5("RAPS5"),
    @XmlEnumValue("S01")
    S_01("S01"),
    @XmlEnumValue("S02")
    S_02("S02"),
    @XmlEnumValue("SB01")
    SB_01("SB01"),
    @XmlEnumValue("SB02")
    SB_02("SB02"),
    @XmlEnumValue("SB03")
    SB_03("SB03"),
    @XmlEnumValue("SB04")
    SB_04("SB04"),
    @XmlEnumValue("SB05")
    SB_05("SB05"),
    @XmlEnumValue("SB06")
    SB_06("SB06"),
    @XmlEnumValue("SB07")
    SB_07("SB07"),
    @XmlEnumValue("SB08")
    SB_08("SB08"),
    @XmlEnumValue("SB09")
    SB_09("SB09"),
    @XmlEnumValue("SB10")
    SB_10("SB10"),
    @XmlEnumValue("SB11")
    SB_11("SB11"),
    @XmlEnumValue("SB13")
    SB_13("SB13"),
    @XmlEnumValue("SB14")
    SB_14("SB14"),
    @XmlEnumValue("SB16")
    SB_16("SB16"),
    @XmlEnumValue("SB17")
    SB_17("SB17"),
    @XmlEnumValue("SB19")
    SB_19("SB19"),
    @XmlEnumValue("SB20")
    SB_20("SB20"),
    @XmlEnumValue("SB21")
    SB_21("SB21"),
    @XmlEnumValue("SB22")
    SB_22("SB22"),
    @XmlEnumValue("SB23")
    SB_23("SB23"),
    @XmlEnumValue("SB25")
    SB_25("SB25"),
    @XmlEnumValue("SB26")
    SB_26("SB26"),
    @XmlEnumValue("SB27")
    SB_27("SB27"),
    @XmlEnumValue("SB28")
    SB_28("SB28"),
    @XmlEnumValue("SB29")
    SB_29("SB29"),
    @XmlEnumValue("SB30")
    SB_30("SB30"),
    @XmlEnumValue("SB31")
    SB_31("SB31"),
    @XmlEnumValue("SB32")
    SB_32("SB32"),
    @XmlEnumValue("SB33")
    SB_33("SB33"),
    @XmlEnumValue("SB34")
    SB_34("SB34"),
    @XmlEnumValue("SB35")
    SB_35("SB35"),
    @XmlEnumValue("SB36")
    SB_36("SB36"),
    @XmlEnumValue("SB37")
    SB_37("SB37"),
    @XmlEnumValue("SB38")
    SB_38("SB38"),
    @XmlEnumValue("SB39")
    SB_39("SB39"),
    @XmlEnumValue("SB40")
    SB_40("SB40"),
    @XmlEnumValue("SB41")
    SB_41("SB41"),
    @XmlEnumValue("SB42")
    SB_42("SB42"),
    @XmlEnumValue("SB43")
    SB_43("SB43"),
    @XmlEnumValue("SB44")
    SB_44("SB44"),
    @XmlEnumValue("SB45")
    SB_45("SB45"),
    @XmlEnumValue("SB46")
    SB_46("SB46"),
    @XmlEnumValue("SB47")
    SB_47("SB47"),
    @XmlEnumValue("SB48")
    SB_48("SB48"),
    @XmlEnumValue("SB49")
    SB_49("SB49"),
    @XmlEnumValue("SB50")
    SB_50("SB50"),
    @XmlEnumValue("SB51")
    SB_51("SB51"),
    @XmlEnumValue("TBA1")
    TBA_1("TBA1"),
    @XmlEnumValue("TBA2")
    TBA_2("TBA2"),
    @XmlEnumValue("TBA3")
    TBA_3("TBA3"),
    @XmlEnumValue("TBA4")
    TBA_4("TBA4"),
    @XmlEnumValue("TBA5")
    TBA_5("TBA5"),
    @XmlEnumValue("TBA6")
    TBA_6("TBA6"),
    @XmlEnumValue("TBA7")
    TBA_7("TBA7"),
    @XmlEnumValue("TBD1")
    TBD_1("TBD1"),
    @XmlEnumValue("TBD2")
    TBD_2("TBD2"),
    @XmlEnumValue("TBD3")
    TBD_3("TBD3"),
    @XmlEnumValue("TBD4")
    TBD_4("TBD4"),
    @XmlEnumValue("TBD5")
    TBD_5("TBD5"),
    @XmlEnumValue("TBD6")
    TBD_6("TBD6"),
    @XmlEnumValue("TBD9")
    TBD_9("TBD9"),
    @XmlEnumValue("TBT1")
    TBT_1("TBT1"),
    @XmlEnumValue("TBT10")
    TBT_10("TBT10"),
    @XmlEnumValue("TBT11")
    TBT_11("TBT11"),
    @XmlEnumValue("TBT12")
    TBT_12("TBT12"),
    @XmlEnumValue("TBT13")
    TBT_13("TBT13"),
    @XmlEnumValue("TBT2")
    TBT_2("TBT2"),
    @XmlEnumValue("TBT3")
    TBT_3("TBT3"),
    @XmlEnumValue("TBT4")
    TBT_4("TBT4"),
    @XmlEnumValue("TBT5")
    TBT_5("TBT5"),
    @XmlEnumValue("TBT6")
    TBT_6("TBT6"),
    @XmlEnumValue("TBT7")
    TBT_7("TBT7"),
    @XmlEnumValue("TBT8")
    TBT_8("TBT8"),
    @XmlEnumValue("TBT9")
    TBT_9("TBT9");
    private final String value;

    ReportIndicatorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReportIndicatorType fromValue(String v) {
        for (ReportIndicatorType c: ReportIndicatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
