
package com.redowl.batch_processing.xmlProceser.enums;

public enum XmlTagEnumMain {

    TRANSACTION("report.transaction", false),

    TRANSACTION_INVOLVED_PARTIES("report.transaction.involved_parties", true),
    PARTY_PERSON_PHONES_PHONE("report.transaction.involved_parties.party.person.phones.phone", true),
    PARTY_PERSON_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.person.addresses.address", true),
    PARTY_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.person.employer_address_id", true),
    PARTY_PERSON_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.person.employer_phone_id", true),
    PARTY_PERSON_IDENTIFICATION("report.transaction.involved_parties.party.person.identification", true),
    PARTY_PERSON_MY_CLIENT_PHONES_PHONE("report.transaction.involved_parties.party.person_my_client.phones.phone", true),
    PARTY_PERSON_MY_CLIENT_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.person_my_client.addresses.address", true),
    PARTY_PERSON_MY_CLIENT_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.person_my_client.employer_address_id", true),
    PARTY_PERSON_MY_CLIENT_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.person_my_client.employer_phone_id", true),
    PARTY_PERSON_MY_CLIENT_IDENTIFICATION("report.transaction.involved_parties.party.person_my_client.identification", true),
    PARTY_ACCOUNT_T_ENTITY_PHONES_PHONE("report.transaction.involved_parties.party.account.t_entity.phones.phone", true),
    PARTY_ACCOUNT_T_ENTITY_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.account.t_entity.addresses.address", true),
    PARTY_ACCOUNT_T_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.involved_parties.party.account.t_entity.director_id.phones.phone", true),
    PARTY_ACCOUNT_T_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.account.t_entity.director_id.addresses.address", true),
    PARTY_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.account.t_entity.director_id.employer_address_id", true),
    PARTY_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.account.t_entity.director_id.employer_phone_id", true),
    PARTY_ACCOUNT_T_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.involved_parties.party.account.t_entity.director_id.identification", true),
    PARTY_ACCOUNT_SIGNATORY_T_PERSON_PHONES_PHONE("report.transaction.involved_parties.party.account.signatory.t_person.phones.phone", true),
    PARTY_ACCOUNT_SIGNATORY_T_PERSON_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.account.signatory.t_person.addresses.address", true),
    PARTY_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.account.signatory.t_person.employer_address_id", true),
    PARTY_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.account.signatory.t_person.employer_phone_id", true),
    PARTY_ACCOUNT_SIGNATORY_T_PERSON_IDENTIFICATION("report.transaction.involved_parties.party.account.signatory.t_person.identification", true),
    PARTY_ACCOUNT_MY_CLIENT_T_ENTITY_PHONES_PHONE("report.transaction.involved_parties.party.account_my_client.t_entity.phones.phone", true),
    PARTY_ACCOUNT_MY_CLIENT_T_ENTITY_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.account_my_client.t_entity.addresses.address", true),
    PARTY_ACCOUNT_MY_CLIENT_T_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.involved_parties.party.account_my_client.t_entity.director_id.phones.phone", true),
    PARTY_ACCOUNT_MY_CLIENT_T_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.account_my_client.t_entity.director_id.addresses.address", true),
    PARTY_ACCOUNT_MY_CLIENT_T_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.account_my_client.t_entity.director_id.employer_address_id", true),
    PARTY_ACCOUNT_MY_CLIENT_T_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.account_my_client.t_entity.director_id.employer_phone_id", true),
    PARTY_ACCOUNT_MY_CLIENT_T_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.involved_parties.party.account_my_client.t_entity.director_id.identification", true),
    PARTY_ACCOUNT_MY_CLIENT_SIGNATORY_T_PERSON_PHONES_PHONE("report.transaction.involved_parties.party.account_my_client.signatory.t_person.phones.phone", true),
    PARTY_ACCOUNT_MY_CLIENT_SIGNATORY_T_PERSON_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.account_my_client.signatory.t_person.addresses.address", true),
    PARTY_ACCOUNT_MY_CLIENT_SIGNATORY_T_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.account_my_client.signatory.t_person.employer_address_id", true),
    PARTY_ACCOUNT_MY_CLIENT_SIGNATORY_T_PERSON_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.account_my_client.signatory.t_person.employer_phone_id", true),
    PARTY_ACCOUNT_MY_CLIENT_SIGNATORY_T_PERSON_IDENTIFICATION("report.transaction.involved_parties.party.account_my_client.signatory.t_person.identification", true),
    PARTY_ENTITY_PHONES_PHONE("report.transaction.involved_parties.party.entity.phones.phone", true),
    PARTY_ENTITY_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.entity.addresses.address", true),
    PARTY_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.involved_parties.party.entity.director_id.phones.phone", true),
    PARTY_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.entity.director_id.addresses.address", true),
    PARTY_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.entity.director_id.employer_address_id", true),
    PARTY_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.entity.director_id.employer_phone_id", true),
    PARTY_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.involved_parties.party.entity.director_id.identification", true),
    PARTY_ENTITY_MY_CLIENT_PHONES_PHONE("report.transaction.involved_parties.party.entity_my_client.phones.phone", true),
    PARTY_ENTITY_MY_CLIENT_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.entity_my_client.addresses.address", true),
    PARTY_ENTITY_MY_CLIENT_DIRECTOR_ID_PHONES_PHONE("report.transaction.involved_parties.party.entity_my_client.director_id.phones.phone", true),
    PARTY_ENTITY_MY_CLIENT_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.involved_parties.party.entity_my_client.director_id.addresses.address", true),
    PARTY_ENTITY_MY_CLIENT_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.involved_parties.party.entity_my_client.director_id.employer_address_id", true),
    PARTY_ENTITY_MY_CLIENT_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.involved_parties.party.entity_my_client.director_id.employer_phone_id", true),
    PARTY_ENTITY_MY_CLIENT_DIRECTOR_ID_IDENTIFICATION("report.transaction.involved_parties.party.entity_my_client.director_id.identification", true),

    T_FROM_MY_CLIENT("report.transaction.t_from_my_client", true),
    T_FROM_MY_CLIENT_FROM_FOREIGN_CURRENCY("report.transaction.t_from_my_client.from_foreign_currency", true),
    T_FROM_MY_CLIENT_T_CONDUCTOR("report.transaction.t_from_my_client.t_conductor", true),
    T_FROM_MY_CLIENT_T_CONDUCTOR_PHONES_PHONE("report.transaction.t_from_my_client.t_conductor.phones.phone", true),
    T_FROM_MY_CLIENT_T_CONDUCTOR_ADDRESSES_ADDRESS("report.transaction.t_from_my_client.t_conductor.addresses.address", true),
    T_FROM_MY_CLIENT_T_CONDUCTOR_EMPLOYER_ADDRESS_ID("report.transaction.t_from_my_client.t_conductor.employer_address_id", true),
    T_FROM_MY_CLIENT_T_CONDUCTOR_EMPLOYER_PHONE_ID("report.transaction.t_from_my_client.t_conductor.employer_phone_id", true),
    T_FROM_MY_CLIENT_T_CONDUCTOR_IDENTIFICATION("report.transaction.t_from_my_client.t_conductor.identification", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT("report.transaction.t_from_my_client.from_account", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY("report.transaction.t_from_my_client.from_account.t_entity", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY_PHONES_PHONE("report.transaction.t_from_my_client.from_account.t_entity.phones.phone", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_from_my_client.from_account.t_entity.addresses.address", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_from_my_client.from_account.t_entity.director_id.phones.phone", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_from_my_client.from_account.t_entity.director_id.addresses.address", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_from_my_client.from_account.t_entity.director_id.employer_address_id", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_from_my_client.from_account.t_entity.director_id.employer_phone_id", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_from_my_client.from_account.t_entity.director_id.identification", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_SIGNATORY_T_PERSON_PHONES_PHONE("report.transaction.t_from_my_client.from_account.signatory.t_person.phones.phone", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_SIGNATORY_T_PERSON_ADDRESSES_ADDRESS("report.transaction.t_from_my_client.from_account.signatory.t_person.addresses.address", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_from_my_client.from_account.signatory.t_person.employer_address_id", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_from_my_client.from_account.signatory.t_person.employer_phone_id", true),
    T_FROM_MY_CLIENT_FROM_ACCOUNT_SIGNATORY_T_PERSON_IDENTIFICATION("report.transaction.t_from_my_client.from_account.signatory.t_person.identification", true),
    T_FROM_MY_CLIENT_FROM_PERSON("report.transaction.t_from_my_client.from_person", true),
    T_FROM_MY_CLIENT_FROM_PERSON_PHONES_PHONE("report.transaction.t_from_my_client.from_person.phones.phone", true),
    T_FROM_MY_CLIENT_FROM_PERSON_ADDRESSES_ADDRESS("report.transaction.t_from_my_client.from_person.addresses.address", true),
    T_FROM_MY_CLIENT_FROM_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_from_my_client.from_person.employer_address_id", true),
    T_FROM_MY_CLIENT_FROM_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_from_my_client.from_person.employer_phone_id", true),
    T_FROM_MY_CLIENT_FROM_PERSON_IDENTIFICATION("report.transaction.t_from_my_client.from_person.identification", true),
    T_FROM_MY_CLIENT_FROM_ENTITY("report.transaction.t_from_my_client.from_entity", true),
    T_FROM_MY_CLIENT_FROM_ENTITY_PHONES_PHONE("report.transaction.t_from_my_client.from_entity.phones.phone", true),
    T_FROM_MY_CLIENT_FROM_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_from_my_client.from_entity.addresses.address", true),
    T_FROM_MY_CLIENT_FROM_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_from_my_client.from_entity.director_id.phones.phone", true),
    T_FROM_MY_CLIENT_FROM_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_from_my_client.from_entity.director_id.addresses.address", true),
    T_FROM_MY_CLIENT_FROM_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_from_my_client.from_entity.director_id.employer_address_id", true),
    T_FROM_MY_CLIENT_FROM_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_from_my_client.from_entity.director_id.employer_phone_id", true),
    T_FROM_MY_CLIENT_FROM_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_from_my_client.from_entity.director_id.identification", true),


    T_FROM("report.transaction.t_from", true),
    T_FROM_FROM_FOREIGN_CURRENCY("report.transaction.t_from.from_foreign_currency", true),
    T_FROM_T_CONDUCTOR("report.transaction.t_from.t_conductor", true),
    T_FROM_T_CONDUCTOR_PHONES_PHONE("report.transaction.t_from.t_conductor.phones.phone", true),
    T_FROM_T_CONDUCTOR_ADDRESSES_ADDRESS("report.transaction.t_from.t_conductor.addresses.address", true),
    T_FROM_T_CONDUCTOR_EMPLOYER_ADDRESS_ID("report.transaction.t_from.t_conductor.employer_address_id", true),
    T_FROM_T_CONDUCTOR_EMPLOYER_PHONE_ID("report.transaction.t_from.t_conductor.employer_phone_id", true),
    T_FROM_T_CONDUCTOR_IDENTIFICATION("report.transaction.t_from.t_conductor.identification", true),
    T_FROM_FROM_ACCOUNT("report.transaction.t_from.from_account", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY("report.transaction.t_from.from_account.t_entity", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY_PHONES_PHONE("report.transaction.t_from.from_account.t_entity.phones.phone", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_from.from_account.t_entity.addresses.address", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_from.from_account.t_entity.director_id.phones.phone", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_from.from_account.t_entity.director_id.addresses.address", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_from.from_account.t_entity.director_id.employer_address_id", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_from.from_account.t_entity.director_id.employer_phone_id", true),
    T_FROM_FROM_ACCOUNT_T_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_from.from_account.t_entity.director_id.identification", true),
    T_FROM_FROM_ACCOUNT_SIGNATORY_T_PERSON_PHONES_PHONE("report.transaction.t_from.from_account.signatory.t_person.phones.phone", true),
    T_FROM_FROM_ACCOUNT_SIGNATORY_T_PERSON_ADDRESSES_ADDRESS("report.transaction.t_from.from_account.signatory.t_person.addresses.address", true),
    T_FROM_FROM_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_from.from_account.signatory.t_person.employer_address_id", true),
    T_FROM_FROM_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_from.from_account.signatory.t_person.employer_phone_id", true),
    T_FROM_FROM_ACCOUNT_SIGNATORY_T_PERSON_IDENTIFICATION("report.transaction.t_from.from_account.signatory.t_person.identification", true),
    T_FROM_FROM_PERSON("report.transaction.t_from.from_person", true),
    T_FROM_FROM_PERSON_PHONES_PHONE("report.transaction.t_from.from_person.phones.phone", true),
    T_FROM_FROM_PERSON_ADDRESSES_ADDRESS("report.transaction.t_from.from_person.addresses.address", true),
    T_FROM_FROM_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_from.from_person.employer_address_id", true),
    T_FROM_FROM_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_from.from_person.employer_phone_id", true),
    T_FROM_FROM_PERSON_IDENTIFICATION("report.transaction.t_from.from_person.identification", true),
    T_FROM_FROM_ENTITY("report.transaction.t_from.from_entity", true),
    T_FROM_FROM_ENTITY_PHONES_PHONE("report.transaction.t_from.from_entity.phones.phone", true),
    T_FROM_FROM_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_from.from_entity.addresses.address", true),
    T_FROM_FROM_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_from.from_entity.director_id.phones.phone", true),
    T_FROM_FROM_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_from.from_entity.director_id.addresses.address", true),
    T_FROM_FROM_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_from.from_entity.director_id.employer_address_id", true),
    T_FROM_FROM_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_from.from_entity.director_id.employer_phone_id", true),
    T_FROM_FROM_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_from.from_entity.director_id.identification", true),


    T_TO_MY_CLIENT("report.transaction.t_to_my_client", true),
    T_TO_MY_CLIENT_TO_FOREIGN_CURRENCY("report.transaction.t_to_my_client.to_foreign_currency", true),
    T_TO_MY_CLIENT_TO_ACCOUNT("report.transaction.t_to_my_client.to_account", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY("report.transaction.t_to_my_client.to_account.t_entity", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY_PHONES_PHONE("report.transaction.t_to_my_client.to_account.t_entity.phones.phone", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_to_my_client.to_account.t_entity.addresses.address", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_to_my_client.to_account.t_entity.director_id.phones.phone", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_to_my_client.to_account.t_entity.director_id.addresses.address", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_to_my_client.to_account.t_entity.director_id.employer_address_id", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_to_my_client.to_account.t_entity.director_id.employer_phone_id", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_to_my_client.to_account.t_entity.director_id.identification", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_SIGNATORY_T_PERSON_PHONES_PHONE("report.transaction.t_to_my_client.to_account.signatory.t_person.phones.phone", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_SIGNATORY_T_PERSON_ADDRESSES_ADDRESS("report.transaction.t_to_my_client.to_account.signatory.t_person.addresses.address", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_to_my_client.to_account.signatory.t_person.employer_address_id", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_to_my_client.to_account.signatory.t_person.employer_phone_id", true),
    T_TO_MY_CLIENT_TO_ACCOUNT_SIGNATORY_T_PERSON_IDENTIFICATION("report.transaction.t_to_my_client.to_account.signatory.t_person.identification", true),
    T_TO_MY_CLIENT_TO_PERSON("report.transaction.t_to_my_client.to_person", true),
    T_TO_MY_CLIENT_TO_PERSON_PHONES_PHONE("report.transaction.t_to_my_client.to_person.phones.phone", true),
    T_TO_MY_CLIENT_TO_PERSON_ADDRESSES_ADDRESS("report.transaction.t_to_my_client.to_person.addresses.address", true),
    T_TO_MY_CLIENT_TO_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_to_my_client.to_person.employer_address_id", true),
    T_TO_MY_CLIENT_TO_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_to_my_client.to_person.employer_phone_id", true),
    T_TO_MY_CLIENT_TO_PERSON_IDENTIFICATION("report.transaction.t_to_my_client.to_person.identification", true),
    T_TO_MY_CLIENT_TO_ENTITY("report.transaction.t_to_my_client.to_entity", true),
    T_TO_MY_CLIENT_TO_ENTITY_PHONES_PHONE("report.transaction.t_to_my_client.to_entity.phones.phone", true),
    T_TO_MY_CLIENT_TO_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_to_my_client.to_entity.addresses.address", true),
    T_TO_MY_CLIENT_TO_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_to_my_client.to_entity.director_id.phones.phone", true),
    T_TO_MY_CLIENT_TO_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_to_my_client.to_entity.director_id.addresses.address", true),
    T_TO_MY_CLIENT_TO_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_to_my_client.to_entity.director_id.employer_address_id", true),
    T_TO_MY_CLIENT_TO_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_to_my_client.to_entity.director_id.employer_phone_id", true),
    T_TO_MY_CLIENT_TO_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_to_my_client.to_entity.director_id.identification", true),


    T_TO("report.transaction.t_to", true),
    T_TO_TO_FOREIGN_CURRENCY("report.transaction.t_to.to_foreign_currency", true),
    T_TO_TO_ACCOUNT("report.transaction.t_to.to_account", true),
    T_TO_TO_ACCOUNT_T_ENTITY("report.transaction.t_to.to_account.t_entity", true),
    T_TO_TO_ACCOUNT_T_ENTITY_PHONES_PHONE("report.transaction.t_to.to_account.t_entity.phones.phone", true),
    T_TO_TO_ACCOUNT_T_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_to.to_account.t_entity.addresses.address", true),
    T_TO_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_to.to_account.t_entity.director_id.phones.phone", true),
    T_TO_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_to.to_account.t_entity.director_id.addresses.address", true),
    T_TO_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_to.to_account.t_entity.director_id.employer_address_id", true),
    T_TO_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_to.to_account.t_entity.director_id.employer_phone_id", true),
    T_TO_TO_ACCOUNT_T_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_to.to_account.t_entity.director_id.identification", true),
    T_TO_TO_ACCOUNT_SIGNATORY_T_PERSON_PHONES_PHONE("report.transaction.t_to.to_account.signatory.t_person.phones.phone", true),
    T_TO_TO_ACCOUNT_SIGNATORY_T_PERSON_ADDRESSES_ADDRESS("report.transaction.t_to.to_account.signatory.t_person.addresses.address", true),
    T_TO_TO_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_to.to_account.signatory.t_person.employer_address_id", true),
    T_TO_TO_ACCOUNT_SIGNATORY_T_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_to.to_account.signatory.t_person.employer_phone_id", true),
    T_TO_TO_ACCOUNT_SIGNATORY_T_PERSON_IDENTIFICATION("report.transaction.t_to.to_account.signatory.t_person.identification", true),
    T_TO_TO_PERSON("report.transaction.t_to.to_person", true),
    T_TO_TO_PERSON_PHONES_PHONE("report.transaction.t_to.to_person.phones.phone", true),
    T_TO_TO_PERSON_ADDRESSES_ADDRESS("report.transaction.t_to.to_person.addresses.address", true),
    T_TO_TO_PERSON_EMPLOYER_ADDRESS_ID("report.transaction.t_to.to_person.employer_address_id", true),
    T_TO_TO_PERSON_EMPLOYER_PHONE_ID("report.transaction.t_to.to_person.employer_phone_id", true),
    T_TO_TO_PERSON_IDENTIFICATION("report.transaction.t_to.to_person.identification", true),
    T_TO_TO_ENTITY("report.transaction.t_to.to_entity", true),
    T_TO_TO_ENTITY_PHONES_PHONE("report.transaction.t_to.to_entity.phones.phone", true),
    T_TO_TO_ENTITY_ADDRESSES_ADDRESS("report.transaction.t_to.to_entity.addresses.address", true),
    T_TO_TO_ENTITY_DIRECTOR_ID_PHONES_PHONE("report.transaction.t_to.to_entity.director_id.phones.phone", true),
    T_TO_TO_ENTITY_DIRECTOR_ID_ADDRESSES_ADDRESS("report.transaction.t_to.to_entity.director_id.addresses.address", true),
    T_TO_TO_ENTITY_DIRECTOR_ID_EMPLOYER_ADDRESS_ID("report.transaction.t_to.to_entity.director_id.employer_address_id", true),
    T_TO_TO_ENTITY_DIRECTOR_ID_EMPLOYER_PHONE_ID("report.transaction.t_to.to_entity.director_id.employer_phone_id", true),
    T_TO_TO_ENTITY_DIRECTOR_ID_IDENTIFICATION("report.transaction.t_to.to_entity.director_id.identification", true);


    private final String tag;
    private final boolean repeatable;

    XmlTagEnumMain(String tag, boolean repeatable) {
        this.tag = tag;
        this.repeatable = repeatable;
    }

    public String getTag() {
        return tag;
    }

    public boolean isRepeatable() {
        return repeatable;
    }
}
